Color struct and class type keywords
hicknhack-software/semantic-colorizer pull request #2
Opened 2016-09-23 08:18 UTC by darress

I think the keyword int and struct type Int32 should be colored the same way as they are one and the same. This little change does just that.

2016-09-25 21:16 UTC, arBmind commented on SemanticColorizer/SemanticColorizer.cs
> +            var comparer = StringComparer.InvariantCultureIgnoreCase;
It seems `comparer` is not used.

2016-09-25 21:20 UTC, arBmind commented on SemanticColorizer/SemanticColorizer.cs
> -                   where comparer.Compare(cs.ClassificationType, "identifier") == 0
`comparer` is unused here as well.

2016-09-25 21:24 UTC, arBmind commented on SemanticColorizer/SemanticColorizer.cs
> +using System.IO;
Are these namespaces really used?

2016-09-25 21:30 UTC, arBmind commented on SemanticColorizer/Constants.cs
> +        public const String TypeStructFormat = "struct name";
these string values are default formats? - I guess there could be a named constant somewhere else in Roslyn.

2016-09-25 21:30 UTC, arBmind requested changes
It seems your changes are really C# specific. With this change Colorizer will not work for the other Roslyn languages.
I guess this would need a branch for this. The TypeSpecial & TypeNormal formats have to stay in use for all other languages.

I am also unsure if this is worth all the troubles.

2018-05-13 21:44 UTC, arBmind commented
A similar feature was just merged.

Thank you for the inspiration!

2018-05-13 21:44 UTC, closed without merging

2018-05-17 11:54 UTC, darress commented
You are welcome.